[package]
name = "basic_example_proto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
databricks-zerobus-ingest-sdk = { path = "../../sdk" }
prost = "0.14.1"
prost-reflect = "0.16.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
